"""removed_unique_constraint_from_conversation_table

Revision ID: f8afd683b329
Revises: c16985ce8af3
Create Date: 2025-08-31 13:22:14.143028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8afd683b329'
down_revision: Union[str, None] = 'c16985ce8af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_sender_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_sender_id'), 'conversations', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_sender_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_sender_id'), 'conversations', ['sender_id'], unique=True)
    # ### end Alembic commands ###
